### ISSUE TITLE
`CookieStore.hydrate` fails when running in Node.js env because `localStorage` is undefined

### ISSUE THREAD

**Issue by neilime** [mswjs/cookies#7]
I am  using `setupServer` of `msw/node` to mock endpoint for tests. 

I got the following error: 

```
    TypeError: Cannot read property '_origin' of null

      at Window.get localStorage [as localStorage] (../../../../node_modules/jsdom/lib/jsdom/browser/Window.js:420:50)
      at CookieStore.hydrate (../../../../node_modules/msw/node/lib/index.js:7448:34)
      at setRequestCookies (../../../../node_modules/msw/node/lib/index.js:7549:17)
      at ../../../../node_modules/msw/node/lib/index.js:7609:21
      at ../../../../node_modules/msw/node/lib/index.js:53:71
      at __awaiter (../../../../node_modules/msw/node/lib/index.js:49:12)
      at resolver (../../../../node_modules/msw/node/lib/index.js:7583:24)
      at ClientRequestOverride.<anonymous> (../../../../node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/createClientRequestOverride.ts:189:9)
```

The error occured because the `localStorage` is undefined. 

I know I can mock it, but it will be good that we don't have to.

BTW, thank you for all of `msw/*` packages, very usefull

**Comment by kettanaito** [comment]
Hey, @neilime. Thank you for raising this and for the warm feedback!

The issue seems to be with our current safeguard against running in Node.js:

https://github.com/mswjs/cookies/blob/7865054e0a143a31f652f4eecaa20b2726ec4c4a/src/CookieStore.ts#L122-L124

We don't account for running in JSDOM, which would have the `window` object polyfilled but `localStorage` would still be missing:

https://github.com/mswjs/cookies/blob/7865054e0a143a31f652f4eecaa20b2726ec4c4a/src/CookieStore.ts#L25

I think the right approach here is to rewrite `supportsPresistency` to `typeof localStorage !== 'undefined'`. The library would still work in Node.js because it'll just skip all the persistence logic and use the internal `this.store` map to act as a persistence layer.

**Comment by neilime** [comment]
Sure I will do it today

**Comment by neilime** [comment]
Done @kettanaito: https://github.com/mswjs/cookies/pull/8
